# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2020 Oplus. All rights reserved.
obj-$(CONFIG_OPLUS_FEATURE_OPROJECT) 	+= oplus_project.o
obj-$(CONFIG_OPLUS_FEATURE_ZRAM_OPT)     += oplus_performance/oplus_mm/zram_opt/
obj-$(CONFIG_COLOR_CTRL_V2) += colorctrl.o

#obj-y += oplus_performance/foreground_io_opt/
obj-y += network/

#Add for NandSwap
obj-$(CONFIG_NANDSWAP)		+= oplus_performance/oplus_nandswap/
