#!/bin/bash
DEVICE=apollo
cd ..
MAIN=$PWD
cd kernel_xiaomi_${DEVICE}
KERNEL_DIR=$PWD
ANYKERNEL_DIR=$KERNEL_DIR/AnyKernel3
CLANG_DIR=$MAIN/zyc-clang
DEFCONFIG=vendor/${DEVICE}_defconfig
KERNELVER=$(make kernelversion)

if [[ -z "${JTHREAD}" ]]; then
    COUNT="$(grep -c '^processor' /proc/cpuinfo)"
    export JTHREAD="$((COUNT + 2))"
fi

echo "cleaning..."
make clean && make mrproper
mkdir -p out
clear
BUILD_START=$(date +"%s")

make O=out ARCH=arm64 $DEFCONFIG

PATH="$CLANG_DIR/bin:${PATH}" \
make 				O=out \
				ARCH=arm64 \
				CC=clang \
				CROSS_COMPILE=aarch64-linux-gnu- \
				CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
				-j${JTHREAD}

if [[ -f $KERNEL_DIR/out/arch/arm64/boot/Image.gz-dtb ]] && [[ -f $KERNEL_DIR/out/arch/arm64/boot/dtbo.img ]]; then

	mv $KERNEL_DIR/out/arch/arm64/boot/Image.gz-dtb $ANYKERNEL_DIR/
	mv $KERNEL_DIR/out/arch/arm64/boot/dtbo.img $ANYKERNEL_DIR/
	cd $ANYKERNEL_DIR
	echo ""
	echo "zipping"
	DATE_CLOCK=$(date +'%H%M-%d%m%Y')
	ZIPNAME=$KERNELVER-Oxygen+-$DATE_CLOCK.zip
	zip -r9 $ZIPNAME META-INF ramdisk tools anykernel.sh banner Image.gz-dtb dtbo.img
	mv $ZIPNAME $KERNEL_DIR/
	echo ""

	echo "Cleaning AnyKernel3 dir"
	echo ""
	rm -rf $ANYKERNEL_DIR/*.zip
	rm -rf $ANYKERNEL_DIR/Image.gz-dtb
	rm -rf $ANYKERNEL_DIR/dtbo.img
	echo "****** build done! ******"
	echo ""
	echo "Your kernel zip name is $ZIPNAME"
	echo ""
	BUILD_END=$(date +"%s")
	DIFF=$(($BUILD_END - $BUILD_START))
	echo -e "Build completed in '$(($DIFF / 60))' minute(s) and '$(($DIFF % 60))' seconds"
else
	echo " Kernel build failed! abort zipping..."
fi

rm -rf $KERNEL_DIR/out/
